Conditions type
EstebanEstoc/SICAC pull request #25
Opened 2020-12-27 11:24 UTC by brobin002

icons Actions et Conditions

2020-12-30 10:16 UTC, EstebanEstoc requested changes

2020-12-30 10:16 UTC, EstebanEstoc commented on SICAC/data/Conditions.js
> +        Title: "Hour",
Ca serait mieux de mettre événement du calendrier

2020-12-30 17:10 UTC, jdeguillaume commented on SICAC/data/Conditions.js
> +        Title: "Hour",
Oui au final on a dit qu'on enlevait le truc de l'heure ^^

2021-01-04 10:06 UTC, EstebanEstoc approved these changes

2021-01-04 10:06 UTC, merged